<?php
$globals = $this->globals ;
/**
 * @version		1.0.0 camassistant $
 * @package		camassistant
 * @copyright	Copyright © 2010 - All rights reserved.
 * @license		GNU/GPL
 * @author
 * @author mail	nobody@nobody.com
 *
 *
 * @MVC architecture generated by MVC generator tool at http://www.alphaplug.com
 */

// no direct access
defined('_JEXEC') or die('Restricted access');
JHTML::_('behavior.modal');
JHTML::_('behavior.calendar');
jimport( 'joomla.html.html' );
$propertyList=$this->propertyList;
$industryList=$this->industryList;
$user=& JFactory::getuser();
?>

<link rel="stylesheet" media="all" type="text/css" href="<?php echo Juri::base(); ?>components/com_camassistant/skin/css/jquery1.css" />
<script type="text/javascript" src="<?php echo Juri::base(); ?>components/com_camassistant/skin/js/jquery-1.4.4.min.js"></script>
<script type="text/javascript" src="<?php echo Juri::base(); ?>components/com_camassistant/skin/js/jquery-ui-1.8.6.custom.min.js"></script>
<script type="text/javascript" src="<?php echo Juri::base(); ?>components/com_camassistant/skin/js/jquery-ui-timepicker-addon.js"></script>
<script type="text/javascript">
function PrintDiv() {    
	var divToPrint = document.getElementById('vender_right2');
    var popupWin = window.open('', '_blank', 'width=300,height=300');
    popupWin.document.open();
    popupWin.document.write('<html><body onload="window.print()">' + divToPrint.innerHTML + '</html>');
    popupWin.document.close(); 	
		}	
</script>
	 
<script>
G = jQuery.noConflict();
function fn_submitRFP(rfpType)
{
	frm=document.adminForm;
	frm.rfp_type.value=rfpType;
	frm.submit();
}
</script>
<style type="text/css">
.checkbox, .radio {
	width: 19px;
	height: 25px;
	padding: 0 5px 0 0;
	background: url(checkbox.png) no-repeat;
	display: block;
	clear: left;
	float: left;
}
.radio {
	background: url(radio.png) no-repeat;
}
.select {
	position: absolute;
	width: 158px; /* With the padding included, the width is 190 pixels: the actual width of the image. */
	height: 21px;
	padding: 0 24px 0 8px;
	color: #fff;
	font: 12px/21px arial,sans-serif;
	background: url(select.png) no-repeat;
	overflow: hidden;
}

</style>
<script type="text/javascript">
var checkboxHeight = "25";
var radioHeight = "25";
var selectWidth = "190";

document.write('<style type="text/css">input.styled { display: none; } select.styled { position: relative; width: ' + selectWidth + 'px; opacity: 0; filter: alpha(opacity=0); z-index: 5; } .disabled { opacity: 0.5; filter: alpha(opacity=50); }</style>');

var Custom = {
	init: function() {
		var inputs = document.getElementsByTagName("input"), span = Array(), textnode, option, active;
		for(a = 0; a < inputs.length; a++) {
			if((inputs[a].type == "checkbox" || inputs[a].type == "radio") && inputs[a].className.indexOf("styled") > -1) {
				span[a] = document.createElement("span");
				span[a].className = inputs[a].type;

				if(inputs[a].checked == true) {
					if(inputs[a].type == "checkbox") {
						position = "0 -" + (checkboxHeight*2) + "px";
						span[a].style.backgroundPosition = position;
					} else {
						position = "0 -" + (radioHeight*2) + "px";
						span[a].style.backgroundPosition = position;
					}
				}
				inputs[a].parentNode.insertBefore(span[a], inputs[a]);
				inputs[a].onchange = Custom.clear;
				if(!inputs[a].getAttribute("disabled")) {
					span[a].onmousedown = Custom.pushed;
					span[a].onmouseup = Custom.check;
				} else {
					span[a].className = span[a].className += " disabled";
				}
			}
		}
		inputs = document.getElementsByTagName("select");
		for(a = 0; a < inputs.length; a++) {
			if(inputs[a].className.indexOf("styled") > -1) {
				option = inputs[a].getElementsByTagName("option");
				active = option[0].childNodes[0].nodeValue;
				textnode = document.createTextNode(active);
				for(b = 0; b < option.length; b++) {
					if(option[b].selected == true) {
						textnode = document.createTextNode(option[b].childNodes[0].nodeValue);
					}
				}
				span[a] = document.createElement("span");
				span[a].className = "select";
				span[a].id = "select" + inputs[a].name;
				span[a].appendChild(textnode);
				inputs[a].parentNode.insertBefore(span[a], inputs[a]);
				if(!inputs[a].getAttribute("disabled")) {
					inputs[a].onchange = Custom.choose;
				} else {
					inputs[a].previousSibling.className = inputs[a].previousSibling.className += " disabled";
				}
			}
		}
		document.onmouseup = Custom.clear;
	},
	pushed: function() {
		element = this.nextSibling;
		if(element.checked == true && element.type == "checkbox") {
			this.style.backgroundPosition = "0 -" + checkboxHeight*3 + "px";
		} else if(element.checked == true && element.type == "radio") {
			this.style.backgroundPosition = "0 -" + radioHeight*3 + "px";
		} else if(element.checked != true && element.type == "checkbox") {
			this.style.backgroundPosition = "0 -" + checkboxHeight + "px";
		} else {
			this.style.backgroundPosition = "0 -" + radioHeight + "px";
		}
	},
	check: function() {
		element = this.nextSibling;
		if(element.checked == true && element.type == "checkbox") {
			this.style.backgroundPosition = "0 0";
			element.checked = false;
		} else {
			if(element.type == "checkbox") {
				this.style.backgroundPosition = "0 -" + checkboxHeight*2 + "px";
			} else {
				this.style.backgroundPosition = "0 -" + radioHeight*2 + "px";
				group = this.nextSibling.name;
				inputs = document.getElementsByTagName("input");
				for(a = 0; a < inputs.length; a++) {
					if(inputs[a].name == group && inputs[a] != this.nextSibling) {
						inputs[a].previousSibling.style.backgroundPosition = "0 0";
					}
				}
			}
			element.checked = true;
		}
	},
	clear: function() {
		inputs = document.getElementsByTagName("input");
		for(var b = 0; b < inputs.length; b++) {
			if(inputs[b].type == "checkbox" && inputs[b].checked == true && inputs[b].className.indexOf("styled") > -1) {
				inputs[b].previousSibling.style.backgroundPosition = "0 -" + checkboxHeight*2 + "px";
			} else if(inputs[b].type == "checkbox" && inputs[b].className.indexOf("styled") > -1) {
				inputs[b].previousSibling.style.backgroundPosition = "0 0";
			} else if(inputs[b].type == "radio" && inputs[b].checked == true && inputs[b].className.indexOf("styled") > -1) {
				inputs[b].previousSibling.style.backgroundPosition = "0 -" + radioHeight*2 + "px";
			} else if(inputs[b].type == "radio" && inputs[b].className.indexOf("styled") > -1) {
				inputs[b].previousSibling.style.backgroundPosition = "0 0";
			}
		}
	},
	choose: function() {
		option = this.getElementsByTagName("option");
		for(d = 0; d < option.length; d++) {
			if(option[d].selected == true) {
				document.getElementById("select" + this.name).childNodes[0].nodeValue = option[d].childNodes[0].nodeValue;
			}
		}
	}
}
window.onload = Custom.init;

function getpopuppics(pid){
el='<?php  echo Juri::base(); ?>index2.php?option=com_camassistant&controller=rfp&task=uploadpropertypic&pid='+pid;
var options = $merge(options || {}, Json.evaluate("{handler: 'iframe', size: {x: 500, y:350}}"))
SqueezeBox.fromElement(el,options);
}

</script>
<style type="text/css">
.white_light_link {
	background-color:#FFF;
	border:1px solid #5096DB;
	display:none;
	height:250px;
	left:25%;
	overflow:auto;
	padding:5px;
	position:absolute;
	top:800px;
	bottom:0px;
	width:50%;
	z-index:1002;
}
</style>
<div id="vender_right2">
<?php if($_REQUEST['var'] != 'view'){ ?>
<div align="center"><img src="templates/camassistant_left/images/step3.jpg" /></div>
<p style="height:40px;"></p>
<?php } ?>
<form action="<?php echo JRoute::_( 'index.php' );?>" method="post" name="adminForm" id="adminForm" class="form-validate" >
<?php $RFP=$this->userinfo;  ?>
<!-- sof dotshead -->
<?php /*?><div id="dotshead_blue">Review <span style="color:#8A976F;">RFP</span><div style=" float: right;height: 30px;padding: 4px 3px 0 0;width: 135px;"></div></div><?php */?>
<!-- eof dotshead -->

<div id="i_bar">
<div id="i_bar_txt" style="text-align:center;">
<span style="margin-left:53px;"><strong>REQUEST #<?php echo $_REQUEST['rfpid']; ?></strong></span></div>
<div id="i_icon"><?php
 $user = JFactory::getUser();
if ($user->user_type=='12') { ?>
<a style="text-decoration: none;" title="Click here" class="modal" rel="{handler: 'iframe', size: {x: 680, y: 530}}" href="index2.php?option=com_content&amp;view=article&amp;id=95&amp;Itemid=113"><img src="templates/camassistant_left/images/info_icon2.png" style="padding-left:0px; padding-top:0px;"> </a>
<?php } else { ?>
<a style="text-decoration: none;" title="Click here" class="modal" rel="{handler: 'iframe', size: {x: 680, y: 530}}" href="index2.php?option=com_content&amp;view=article&amp;id=60&amp;Itemid=113"><img src="templates/camassistant_left/images/info_icon2.png" style="padding-left:0px; padding-top:0px;"> </a>
<?php } ?></div>
</div>


<!-- sof table pan -->
<div class="table_pannel">


<div class="head_greenbg276" style="padding-left:20px;"><!--sof rfp box-->
<div id="rpf_ifo" style="margin-top:0px;">

<div id="i_bar">
<div id="i_bar_txt_small" style="text-align:center;">
<span style="margin-left:23px;">
<strong>CONTACT INFO</strong>
<?php
 $user = JFactory::getUser();
if ($user->user_type=='12') { ?>
<a style="text-decoration: none;" title="Click here" class="modal" rel="{handler: 'iframe', size: {x: 680, y: 530}}" href="index2.php?option=com_content&amp;view=article&amp;id=96&amp;Itemid=113"><img align="right" style="margin-top: -4px; margin-right: 4px;" alt="info" src="<?php echo Juri::base(); ?>components/com_camassistant/skin/images/info_icon2.png"></a>
<?php } else { ?>
<a style="text-decoration: none;" title="Click here" class="modal" rel="{handler: 'iframe', size: {x: 680, y: 530}}" href="index2.php?option=com_content&amp;view=article&amp;id=94&amp;Itemid=113"><img align="right" style="margin-top: -4px; margin-right: 4px;" alt="info" src="<?php echo Juri::base(); ?>components/com_camassistant/skin/images/info_icon2.png"> </a>
<?php } ?>
 </span></div>
 </div>
 
 
 
<?php $db =& JFactory::getDBO();
$state="SELECT state_name FROM #__state where id='".$RFP->comp_state."'";
		$db->Setquery($state);
		$state_name = $db->loadResult();
		$property_id = JRequest::getVar('property_id','');
		$rfpid = JRequest::getVar('rfpid','');

		if($property_id == ''){
 $propertd="SELECT property_id FROM #__cam_rfpinfo where id='".$rfpid."'";
$db->Setquery($propertd);
$property_id = $db->loadResult();
		}

$property_details="SELECT property_name,tax_id,property_manager_id FROM #__cam_property where id='".$property_id."'";
$db->Setquery($property_details);
$property = $db->loadObject();
$detail="SELECT name,lastname,phone,extension,email FROM #__users where id='".$property->property_manager_id."'";
$db->Setquery($detail);
$user_detail = $db->loadObjectlist();

		?>
    <div id="rpf_ifo_text"><h1 style="line-height:20px;">Property Management Company:</h1>

<?PHP echo $RFP->comp_name;  ?><br />
<?PHP echo $RFP->mailaddress;  ?><br />
<?PHP echo $RFP->comp_city;  ?>, <?PHP echo $state_name;  ?> <?PHP echo $RFP->comp_zip;  ?><br />
P: <?PHP echo $RFP->comp_phno;  ?><br />
F: <?PHP echo $RFP->comp_alt_phno;  ?><br />
<a href="http://<?PHP echo $RFP->comp_website;  ?>" target="_blank"><?PHP echo $RFP->comp_website;  ?></a>
<h1 style="line-height:20px; margin-top:10px;">Property Manager:</h1>
<?PHP echo $user_detail[0]->name;  ?> <?PHP echo $user_detail[0]->lastname;  ?><br />
P: <?PHP echo $user_detail[0]->phone;  ?> (x<?PHP echo $user_detail[0]->extension;  ?>)<br />
<a href="mailto:<?PHP echo $user_detail[0]->email;  ?>">Email Property Manager</a>
<br /><br />
<?php
if($user->user_type == 13 && $user->accounttype=='master')
$itemid = '209';
else if($user->user_type == 13 && $user->accounttype!='master')
$itemid = '209';
else
$itemid = '129';
?>

<a class="modal" id="editlinkmans" rel="{handler:'iframe', size:{x:370, y:300}}" href="index.php?option=com_camassistant&controller=rfp&task=shareinfo&tmpl=component" >EDIT</a>
  </div>
 <?php /*?><a class="modal" rel="{handler:'iframe', size:{x:370, y:300}}" href="index.php?option=com_camassistant&controller=rfp&task=shareinfo&tmpl=component" >
 <img align="right" style="margin-right:-3px;" alt="info sharing preferences" src="<?php echo Juri::base(); ?>components/com_camassistant/skin/images/infosharing.gif"></a><?php */?></div>
    <!--<a href="#"><img height="22" align="right" width="141" alt="info sharing preferences" src="<?php //echo Juri::base(); ?>components/com_camassistant/skin/images/infosharing.gif"></a>-->

	 <?php
$rfpinfo=$this->rfpinfo;
$rfpuploadfiles=$this->rfpuploadfiles;
$rfplinetasks=$this->rfplinetasks;
$rfpreqinfo=$this->rfpreqinfo;

  ?>

</div>
 </div>


  <div  class="proposal_form" style="padding-left:0px;">

<?php
$db=JFactory::getDBO();
$pimage = "SELECT property_image FROM #__cam_property WHERE id='".$property_id."' ";
$db->Setquery($pimage);
$filename = $db->loadResult();
if( $filename ) {
		$path2 = $siteURL."components/com_camassistant/assets/images/property_pictures/";
		$path1 = $filename;
		$image = $path2.$path1;	
		$image = str_replace(' ','%20',$image);
		$apath= getimagesize($image);
		$height_orig=$apath[1];
		$width_orig=$apath[0];
		$aspect_ratio = (float) $height_orig / $width_orig;
		$thumb_width =423;
		$thumb_height = round($thumb_width * $aspect_ratio) ;
		if($thumb_height == 0){
		$thumb_height = '300';
		}		
		$image = "<img  width=".$thumb_width." height=".$thumb_height." src='components/com_camassistant/assets/images/property_pictures/".$filename."'><div class='clear'></div><p style='height:20px'></p>";
		}	
else{
$image = '<a href="javascript:void(0);" onclick="getpopuppics('. $property_id .');" ><img src="templates/camassistant_left/images/uopload.jpg"></a></p>';
$cleamsg = '<div class="clear"></div><p style="height:20px"></p>';
} ?>
<div id="imagediv"><?php echo $image ; ?></div>
<?php echo $cleamsg; ?>

<div id="i_bar">
<div id="i_bar_txt" style="text-align:center; float:none; width:666px;">
<span><strong> BASIC INFORMATION </strong></span>
</div>
</div>

<div style="min-height:350px; margin-top: 6px; padding:5px; font-size:11px;border:1px solid #CDCDCD;">
<div class="signup">
<label><strong>Type of Bidding:</strong> </label>
<?php  
if($rfpinfo->bidding == '' || $rfpinfo->bidding == 'open'){
echo "Open Bidding";
}
else{
echo "Sealed Bidding";
}
?>
</div>
<div class="signup">
<label><strong>Property Name:</strong> </label>
<?php echo str_replace('_',' ',$this->propertyname);?>
</div>


<div class="signup">
<label><strong>Reference Name: </strong></label>
<?php echo $rfpinfo->projectName; ?>
</div>

<div class="signup">
<label><strong>Industry Name:</strong></label>
<?php echo $this->industryname;?>
</div>

<div class="signup">
<label><strong>Proposals Due By:</strong></label>
<?php echo $rfpinfo->proposalDueDate; ?> 	<?php echo $rfpinfo->proposalDueTime; ?>
</div>




<div class="signup2">
<label>
<strong>Site Visit: </strong>
 </label><div class="clear"></div>
 <?php //echo "<pre>"; print_r($rfpinfo); ?>
<?php echo $rfpinfo->site_visit; ?><br/>
<?php /*?>modified by anand kumar 25-7-11<?php */?>
<?php /*?><strong>Bidders Info: </strong><br/><?php */?>
<?php if($rfpinfo->site_visit!='Not Required') { ?>
<?php echo $rfpinfo->bidders_info; }?>
<?php /*?>modified by anand kumar 25-7-11<?php */?>
</div>
<br>
</div>


</div>
<p style="height:50px"></p>
<!-- eof line item pan -->

<div id="i_bar_terms">
<div id="i_bar_txt_terms">
<span> <font style="font-weight:bold; color:#FFF;">SCOPE OF WORK</font></span>
</div></div>

<?php
$i=1;
/*echo "<pre>";
print_r($rfpuploadfiles);*/
/*modified by anand kumar 25-7-11*/

 foreach($rfplinetasks as $linetaks){ ?>
<!--  sof line item pan -->
<?php //echo "<pre>"; print_r($linetaks->taskuploads); ?>
<div id='line_task<?php echo $linetaks->task_id; ?>'>
<p style="height:10px;"></p>
<div class="lineitem_pan_row"><h3 class="lineitemheading">LINE ITEM #<?PHP echo $i; ?></h3>
<div class="lineitem_pan"><strong>Name: </strong><?php  if($linetaks->linetaskname){ echo $linetaks->linetaskname; } ?>

<div  style="border-top:1px solid #CDCDCD;  padding: 4px 0;" ><strong>Description: </strong><?php echo nl2br($linetaks->task_desc); ?></div>
<div  style="border-top:1px solid #CDCDCD;  padding: 4px 0;" ><strong>Line task Files: </strong><br/>
<?php /*?>modified by anand kumar 25-7-11<?php */?><table>
<?php if($linetaks->taskuploads){ ?>
<?php $path=JURI::base();
$link= $path.$linetaks->taskuploads;
$default = 'components/com_camassistant/doc/';
 $uploaded_file= str_replace(' ','',$linetaks->taskuploads);
 
$p_name= str_replace(' ','_',$property->property_name);

$linetaks->taskuploads = str_replace(' ,','',$linetaks->taskuploads);
    $linetaks->taskuploads = str_replace(',,',',',$linetaks->taskuploads);
    $linetaks->taskuploads = str_replace(' ','',$linetaks->taskuploads);
 $uploads= explode(',',$linetaks->taskuploads );   
    if(count($uploads)>0 && count($linetaks->taskuploads)>0 ){ 
        
         for ($l=0;$l<count($uploads);$l++){  ?> 
    <?php  $uploads1=explode('/',$uploads[$l]); 
       if($uploads[$l] && $uploads[$l]!=' '){  
    
 $uploads23=explode('/',$uploads[$l]);
  //echo '<pre>'; print_r($uploads23);
//echo $uploads1;
 // $uploads=explode('/',$linetaks->taskuploads); $upcount=count($uploads);
// echo "Filename:".$linetaks->taskuploads;
if($uploads23[0]=='components' && $uploads23[1]=='com_camassistant' && $uploads23[2]=='doc' ){
 $file_link = str_replace(' ','',$uploads[$l]);
} else if($uploads23[0]=='components' && $uploads23[1]=='com_camassistant' && $uploads23[2]=='assets'){
   $file_link = str_replace(' ','',$uploads[$l]);
 } else {
 $file_link = $default.$p_name.'_'.$property->tax_id.'//'.str_replace(' ','',$uploads[$l]);
 }
// $file_link = $default.$p_name.'_'.$property->tax_id.'//'.$linetaks->taskuploads;
  $file_link= str_replace('// ','/',$file_link); ?>


<?php //echo '<pre>'; print_r($uploads1[$upcount-1]); ?>

<tr><td>
<a href="index.php?option=com_camassistant&controller=popupdocs&task=open&title=<?php echo str_replace(' ','',$uploads1[$upcount-1]); ?>&path=<?php print_r($file_link); ?> "><img src="templates/camassistant_left/images/green.png" alt="download file" align="absmiddle" /></a></td><td><?php   $upcount=count($uploads1); ?> <span style="color:#8FD800"><?php echo $uploads1[$upcount-1]; ?></span></td></tr>
<?php } } } } ?></table>
</div>
<?php // } ?>
<div style="border-top:1px solid #CDCDCD;   padding: 4px 0;">
<?php /*?>modified by anand kumar 25-7-11<?php */?>

<span style="text-align:left;width:300px;"><strong>Require itemized pricing for this line item:</strong> <?php  if($linetaks->is_req_taskvendors=='1'){ echo"Yes"; }else{ echo"No";  } ?></span><br /><br /></div>
</div></div>
<p style="height:10px;"></p>
</div>
<!-- eof line item pan -->
<?php $i++; } ?>
	<div id="newdiv"></div>	 <input name="hidden" type="hidden" id="theValue" value="0">
<?PHP if($DOCS[0]->doc_path){ ?>	<div class="head_greenbg2"><strong>Additional Document/Specifications:</strong></div> <?PHP } ?>
<?php /*?><?php
$i=1;
 foreach($rfpuploadfiles as $rfpupload){ ?>
<!--  sof line item pan -->
<p style="padding-top: 20px;"></p>
<div id="upload_file">
<div class="lineitem_pan_row">
<span class="grey_12"><strong>Additional Document/Specifications #1:</strong>

</span>
<div style="padding: 10px 0pt 10px 5px;" class="lineitem_pan">
<input type="file" name="attachmnent[]" />

</div>
<div style="float: left; padding-left: 10px;">
<input type="checkbox" value="" name="">
<strong>Require</strong> vendors to assign a <strong>Dollar Value </strong>to this Attachment.</div>
<div class="color_butons"><a href="javascript:addEvent2();"><img height="22" width="160" alt="Upload another attachment" src="<?php echo Juri::base(); ?>components/com_camassistant/skin/images/uploadanother.gif"></a>
</div>
<div class="clear"></div>
</div>
</div>
<!-- eof line item pan -->
<?php $i++; } ?>
	<div id="newdiv2"></div>
	<input name="hidden2" type="hidden" id="theValues" value="0">
<!--  sof line item pan -->
<div class="clear"></div><?php */?>
    <?php $DOCS = $this->DOCS_details;
    //echo "<pre>"; print_r($DOCS ); ?>
<?PHP if($DOCS[0]->doc_path){ ?>	<div class="head_greenbg2"><strong>Additional Document/Specifications:</strong></div> <?PHP } ?>
<?php if($DOCS[0]->doc_path){ ?>
<div class="lineitem_pan"> 
<?php 
for($j=0; $j<count($DOCS); $j++)
{

//if($DOCS[$j]->doc_path>0) {
//print_r($DOCS[$j]); ?>
<div class="downloadfile">
<?php
$uploads=explode('/',$DOCS[$j]->doc_path);
$upcount=count($uploads);
$default = 'components/com_camassistant/doc/';
$DOCS[$j]->doc_path = str_replace(' ','',$DOCS[$j]->doc_path);
if($uploads[0]=='components' && $uploads[1]=='com_camassistant' && $uploads[2]=='doc' ){
 $file_link = $DOCS[$j]->doc_path;
 } else if($uploads[0]=='components' && $uploads[1]=='com_camassistant' && $uploads[2]=='assets'){
   $file_link = $DOCS[$j]->doc_path;
 } else {
 $file_link = $default.str_replace(' ','_',$property->property_name).'_'.$property->tax_id.'/'.$DOCS[$j]->doc_path;
 }
//$file_link = $default.str_replace(' ','_',$property->property_name).'_'.$property->tax_id.'/'.$DOCS[$j]->doc_path;
?>
<a href="index.php?option=com_camassistant&controller=popupdocs&task=open&title=<?php print_r($uploads[$upcount-1]); ?>&path=<?php print_r($file_link); ?> "><img src="templates/camassistant_left/images/green.png" alt="download file" align="absmiddle" /></a> <strong><?php  echo $uploads[$upcount-1]; ?><?PHP //echo $DOCS[$j]->title;?></strong>
<div class="clear"></div>
</div>
<!--<div style="float: left; padding-left: 10px;">
<strong>Require vendors to assign a Dollar Value to this Attachment: <?php if($DOCS[$j]->is_req_docvendors=='1'){ echo "Yes"; } else { echo "No"; } ?></strong></div><br/>-->
<!-- eof line item pan -->
<?PHP } ?>
 </div> 
 <?php } ?>
<p style="padding-top: 20px;"></p>
<?php
$Review_reqCatList = $this->Review_reqCatList;
//print_r($Review_reqCatList['main']);
?>
<?php
$generaldata = $this->general_ins;
$autodata = $this->auto_ins;
$workdata = $this->work_ins;
$umbrelladata = $this->umb_ins;
$licdata = $this->lic_ins;
$exist_lic = $this->old_license ;
$exist_workers = $this->old_workers ;
?>
<?php /*?><div class="head_greenbg2"><strong>Special Requirements:</strong></div><?php */?>
<br />
<div id="i_bar_terms_rfp">
<div id="i_bar_txt_terms_rfp">
<span> <font style="font-weight:bold; color:#FFF;">SPECIAL REQUIREMENTS</font></span>
</div></div>
<table cellpadding="0" cellspacing="0" border="0">
	<?php
	if($generaldata || ($exist_workers[1]->req_parentid == '3' && $exist_workers[1]->req_subparentid == '12') ) { $general_main = 'checked="checked"'; $gen_class = 'styled';  
	?>
	<tr><td><input type="checkbox" value="yes" id="generalliability" class="<?php echo $gen_class; ?>" name="generalliability" <?php echo $general_main; ?> /></td><td><strong>General Liability</strong></td></tr>
	<?php } ?>
	<?php 
	if($generaldata || ($exist_workers[1]->req_parentid == '3' && $exist_workers[1]->req_subparentid == '12') ) {
	//echo "<pre>"; print_r($exist_workers); echo "</pre>";
	?>
	<tr><td></td><td>
	<ul class="pre_general" style="pointer-events:none; list-style-type:none;">
		<?php if($generaldata->occur){ $selected_occur = 'checked'; $class = 'styled'; ?>
		<li><table cellpadding="0" cellspacing="0"><tr><td><input type="checkbox" value="yes" name="occur" class="<?php echo $class; ?>" checked="<?php echo $selected_occur; ?>" /></td><td><label>Occur</label></td></tr></table></li>
		<?php } ?>
		<?php if($generaldata->each_occurrence && $generaldata->each_occurrence != '0.00'){ ?>
		<li>Each Occurrence: <span id="greenbolddolor"><?php echo "$".number_format($generaldata->each_occurrence,2); ?></span></li>
		<?php } ?>
		<?php if($generaldata->damage_retend && $generaldata->damage_retend != '0.00'){ ?>
		<li>Damage to Rented Premises: <span id="greenbolddolor"><?php echo "$".number_format($generaldata->damage_retend,2); ?></span></li>
		<?php } ?>
		<?php if($generaldata->med_expenses && $generaldata->med_expenses != '0.00'){ ?>
		<li>Med Expenses: <span id="greenbolddolor"><?php echo "$".number_format($generaldata->med_expenses,2); ?></span></li>
		<?php } ?>
		<?php if($generaldata->personal_inj && $generaldata->personal_inj != '0.00'){ ?>
		<li>Personal & Adv injury: <span id="greenbolddolor"><?php echo "$".number_format($generaldata->personal_inj,2); ?></span></li>
		<?php } ?>
		<?php if( ($generaldata->general_aggr && $generaldata->general_aggr !='0.00' ) || ($exist_workers[1]->req_parentid == '3' && $exist_workers[1]->req_subparentid == '12') ){
			if($exist_workers[1]->price) { 
			$aggregate_price = $exist_workers[1]->price ; 
			$aggregate_price = str_replace(',','',$aggregate_price);
			}
			else { 
			$aggregate_price = $generaldata->general_aggr ; } 
			
		 ?>
		<li>
		<table cellpadding="0" cellspacing="0"><tr><td valign="bottom" style="padding-top:3px;">General Aggregate:&nbsp;</td><td valign="bottom"><span id="greenbolddolor"><?php echo "$".number_format($aggregate_price,2); ?></span> </td>
		<?php } ?>
		<?php if($generaldata->applies_to){ ?>
		<?php if($generaldata->applies_to == 'pol') 
			  $pols = 'checked="checked"';
		      else if($generaldata->applies_to == 'proj')
			  $proj = 'checked="checked"';
			  else if($generaldata->applies_to == 'loc')
			  $loc = 'checked="checked"';
		 ?>
		
		<td valign="top" style="padding-top:2px;">| Applies To: </td>
		<td valign="top" style="padding-top:2px;"><input type="radio" name="applies_to" value="pol" <?php echo $pols; ?>  /></td><td valign="top" style="padding-top:2px;"> Pol&nbsp;&nbsp; </td>
		<td valign="top" style="padding-top:2px;"><input type="radio" name="applies_to" value="proj" <?php echo $proj; ?> /></td><td valign="top" style="padding-top:2px;"> Proj&nbsp;&nbsp;</td>
		<td valign="top" style="padding-top:2px;"><input type="radio" name="applies_to" value="loc" <?php echo $loc; ?> /></td><td valign="top" style="padding-top:2px;"> Loc</li></td></tr></table>
		<?php } ?>
		<?php if($generaldata->products_aggr && $generaldata->products_aggr !='0.00' ){ ?>
		<li>Products - COMP/OP Aggregate: <span id="greenbolddolor"><?php echo "$".number_format($generaldata->products_aggr,2); ?></span></li>
		<?php } ?>
		<?php if($generaldata->waiver_sub == 'yes'){ $waiv = 'checked'; $class_waiver_sub = 'styled'; ?>
		<li><input type="checkbox" value="yes" name="waiver_sub" checked="<?php echo $waiv; ?>" class="<?php echo $class_waiver_sub; ?>" /> <label>Waiver of Subrogation</label></li>
		<?php } ?>
		<?php if($generaldata->primary_noncontr == 'yes'){ $prim = 'checked'; $class_primary_noncontr = 'styled';?>
		<li><input type="checkbox" value="yes" name="primary_noncontr" checked="<?php echo $prim; ?>" class="<?php echo $class_primary_noncontr; ?>" /><label> Primary Non-Contributory</label></li>
		<?php } ?>
		<?php if($generaldata->additional_insured == 'yes'){ $add = 'checked'; $class_additional_insured = 'styled';?>
		<li><input type="checkbox" value="yes" name="additional_insured" checked="<?php echo $add; ?>" class="<?php echo $class_additional_insured; ?>" /><label> List my Company as as "Additional Insured"</label></li>
		<?php } ?>
		<?php if($generaldata->cert_holder == 'yes'){ $cert = 'checked'; $class_cert_holder = 'styled'; ?>
		<li><input type="checkbox" value="yes" name="cert_holder" checked="<?php echo $cert; ?>" class="<?php echo $class_cert_holder; ?>"  /><label> MyVendorCenter listed as Cert. Holder</label></li>
		<?php } ?>
		</ul>		
		</td>
		</td></tr>
	<?php } ?>	
	<tr id="generalliability_sub"></tr>
	<?php
		if($autodata){ $auto_main = 'checked="checked"'; $class_auto="styled"; 
	?>
	<tr><td><input type="checkbox" value="yes" id="autoliability" class="<?php echo $class_auto; ?>" name="autoliability" <?php echo $auto_main; ?> /></td><td><strong>Auto Liability</strong></td></tr>
	<?php } ?>
	<tr><td></td><td>
	<ul class="pre_auto" style="pointer-events:none; list-style-type:none;">
		<?php 
		
			  if($autodata->applies_to_any == 'any') {
			  $any = 'checked="checked"';
			  $class_any = 'styled';
			  }
		      if($autodata->applies_to_owned == 'owned'){
			  $owned = 'checked="checked"';
			  $class_owned = 'styled';
			  }
			  if($autodata->applies_to_nonowned == 'nonowned'){
			  $nonowned = 'checked="checked"';
			  $class_nonowned = 'styled';
			  }
			  if ($autodata->applies_to_hired == 'hired'){
			  $hired = 'checked="checked"';
			  $class_hired = 'styled';
			  }
			  if ($autodata->applies_to_scheduled == 'scheduled'){
			  $scheduled = 'checked="checked"';
			  $class_scheduled = 'styled';
			  }
		?>
		
<?php if($autodata->applies_to_any || $autodata->applies_to_owned || $autodata->applies_to_nonowned || $autodata->applies_to_hired || $autodata->applies_to_scheduled){ ?>
<li>
<table cellpadding="0" cellspacing="0"><tr><td>Applies To: </td>
<?php if($autodata->applies_to_any) { ?><td><input type="checkbox" name="applies_to_any" class="<?php echo $class_any; ?>" value="any" <?php echo $any; ?>  /></td><td> Any&nbsp;&nbsp; </td><?php } ?>
<?php if($autodata->applies_to_owned) { ?><td><input type="checkbox" name="applies_to_owned" class="<?php echo $class_owned; ?>" value="owned" <?php echo $owned; ?> /></td><td>Owned&nbsp;&nbsp;</td><?php } ?>
<?php if($autodata->applies_to_nonowned) { ?><td><input type="checkbox" name="applies_to_nonowned" class="<?php echo $class_nonowned; ?>" value="nonowned" <?php echo $nonowned; ?> /></td><td>Non-Owned&nbsp;&nbsp;</td><?php } ?>
<?php if($autodata->applies_to_hired) { ?><td><input type="checkbox" name="applies_to_hired" class="<?php echo $class_hired; ?>" value="hired" <?php echo $hired; ?> /></td><td>Hired&nbsp;&nbsp;</td><?php } ?>
<?php if($autodata->applies_to_scheduled) { ?><td><input type="checkbox" name="applies_to_scheduled" class="<?php echo $class_scheduled; ?>" value="scheduled" <?php echo $scheduled; ?> /></td><td>Scheduled</td><?php } ?>
</tr></table>
</li>
<?php } ?>

<?php if($autodata->combined_single && $autodata->combined_single != '0.00'){ ?>
		<li>Combined Single Limit: <span id="greenbolddolor"><?php echo "$".number_format($autodata->combined_single,2); ?></span></li>
		<?php } ?>		
		<?php if($autodata->bodily_injusy_person && $autodata->bodily_injusy_person != '0.00'){ ?>
		<li>Bodily Injury - Per Person: <span id="greenbolddolor"><?php echo "$".number_format($autodata->bodily_injusy_person,2); ?></span></li>
		<?php } ?>		
		<?php if($autodata->bodily_injusy_accident && $autodata->bodily_injusy_accident != '0.00'){ ?>
		<li>Bodily Injury - Per Accident: <span id="greenbolddolor"><?php echo "$".number_format($autodata->bodily_injusy_accident,2); ?></span></li>
		<?php } ?>		
		<?php if($autodata->property_damage && $autodata->property_damage != '0.00'){ ?>
		<li>Property Damage - Per Accident: <span id="greenbolddolor"><?php echo "$".number_format($autodata->property_damage,2); ?></span></li>
		<?php } ?>
		<?php if($autodata->waiver){ ?>
		<?php if($autodata->waiver == 'yes'){ $waiv = 'checked="checked"'; $class_waiver = 'styled'; }?>
		<li><input type="checkbox" value="yes" name="waiver" <?php echo $waiv; ?> class="<?php echo $class_waiver; ?>" /> <label>Waiver of Subrogation</label></li>
		<?php } ?>
		<?php if($autodata->primary){ ?>
		<?php if($autodata->primary == 'yes'){ $prim = 'checked="checked"'; $class_primary = 'styled';} ?>
		<li><input type="checkbox" value="yes" name="primary" <?php echo $prim; ?>  class="<?php echo $class_primary; ?>" /> <label>Primary Non-Contributory</label></li>
		<?php } ?>
		<?php if($autodata->additional_ins){ ?>
		<?php if($autodata->additional_ins == 'yes'){ $add = 'checked="checked"'; $class_additional_ins = 'styled';} ?>
		<li><input type="checkbox" value="yes" name="additional_ins" <?php echo $add; ?> class="<?php echo $class_additional_ins; ?>" /><label> List my Company as as "Additional Insured"</label></li>
		<?php } ?>
		<?php if($autodata->cert_holder){ ?>
		<?php if($autodata->cert_holder == 'yes'){ $cert = 'checked="checked"'; $class_cert_holder2 = 'styled';} ?>
		<li><input type="checkbox" value="yes" name="cert_holder" <?php echo $cert; ?> class="<?php echo $class_cert_holder2; ?>"  /> <label>MyVendorCenter listed as Cert. Holder</label></li>
		<?php } ?>
		</ul>
	
	</td></tr>
	<tr id="autoliability_sub"></tr>
	<?php
		if($workdata || $exist_workers[0]->req_subparentid == '11'){ $work_main = 'checked="checked"'; $class_work="styled";
	?>
	<tr><td><input type="checkbox" value="yes" id="workersliability" class="<?php echo $class_work; ?>" name="workersliability" <?php echo $work_main; ?> /></td><td><strong>Worker`s Comp Policy/Employer`s Liability</strong></td></tr>
	<?php } ?>
	<tr><td></td><td>
	<ul class="pre_workers" style="pointer-events:none; list-style-type:none;">
		<?php 
		if($workdata->workers_not == 'not' || $exist_workers[0]->req_id == '19') {
		$not = 'checked="checked"';
		if($workdata->workers_not || $exist_workers[0]->req_id == '19'){ ?>
		<li><input type="radio" id="workers_not" name="workers_not" value="not" <?php echo $not; ?>  /> Worker`s Comp Exemptions NOT accepted</li>
		<?php } ?>	
		<li><ul class="notaccepted" style="list-style-type:none;"><li>	
		<?php if($workdata->each_accident && $workdata->each_accident != '0.00'){ ?>
		<li>Each Accident: <span id="greenbolddolor"><?php echo "$".number_format($workdata->each_accident,2); ?></span></li>
		<?php } ?>		
		<?php if($workdata->disease_policy && $workdata->disease_policy != '0.00'){ ?>
		<li>Desease - Policy Limit: <span id="greenbolddolor"><?php echo "$".number_format($workdata->disease_policy,2); ?></span></li>
		<?php } ?>		
		<?php if($workdata->disease_eachemp && $workdata->disease_eachemp != '0.00'){ ?>
		<li>Desease - Each Employee: <span id="greenbolddolor"><?php echo "$".number_format($workdata->disease_eachemp,2); ?></span></li>
		<?php } ?>
		<?php if($workdata->waiver_work){ ?>
		<?php if($workdata->waiver_work == 'yes'){ $waiver_work = 'checked="checked"'; $class_waiver_work = 'styled';}?>
		<li><input type="checkbox" value="yes" name="waiver_work" <?php echo $waiver_work; ?> class="<?php echo $class_waiver_work; ?>" /><label> Waiver of Subrogation</label></li>
		<?php } ?>
		<?php if($workdata->certholder_work){ ?>
		<?php if($workdata->certholder_work == 'yes'){ $certholder_work = 'checked="checked"'; $class_certholder_work = 'styled';} ?>
		<li><input type="checkbox" value="yes" name="certholder_work" <?php echo $certholder_work; ?> class="<?php echo $class_certholder_work; ?>" /><label> MyVendorCenter listed as Cert. Holder</label></li>
		</li></ul></li>
		<?php } ?>
		<?php 
		}
		else if($workdata->workers_not == 'yes'  || $exist_workers[0]->req_id == '20'){ 
		$workers_accepted = 'checked="checked"';
		?>
		<li><input type="radio" id="workers_yes" name="workers_not" value="yes" <?php echo $workers_accepted; ?>  /> Worker`s Comp Exemptions accepted
		<br />WARNING: Worker`s Comp. Exemption Certificates are commonly mistaken for a Worker`s Comp policy. Please be aware that this "exemption" does NOT offer the property manager/association/building owner any form of protection against liability for an injured worker`s loss of wages and/or medical expenses if an on-the-job injury occurs. Consult your legal advisor for your unique situation, as laws vary by jurisdiction.
		</li>
		<?php } ?>
		</ul>
	
	</td></tr>
	<tr id="workersliability_sub"></tr>
	<?php
		if($umbrelladata){ $umb_main = 'checked="checked"'; $class_umb = 'styled';  
	?>
	<tr><td><input type="checkbox" value="yes" id="umbrellaliability" class="<?php echo $class_umb; ?>" name="umbrellaliability" <?php echo $umb_main; ?> /></td><td><strong>Umbrella Liability</strong></td></tr>
	<?php } ?>
	<tr><td></td><td>
	<ul class="pre_umbrella" style="pointer-events:none; list-style-type:none;">
		
		<?php if($umbrelladata->each_occur && $umbrelladata->each_occur != '0.00'){ ?>
		<li>Each Occurrence: <span id="greenbolddolor"><?php echo "$".number_format($umbrelladata->each_occur,2); ?></span></li>
		<?php } ?>		
		<?php if($umbrelladata->aggregate && $umbrelladata->aggregate != '0.00'){ ?>
		<li>Aggregate: <span id="greenbolddolor"><?php echo "$".number_format($umbrelladata->aggregate,2); ?></span></li>
		<?php } ?>	
		<?php if($umbrelladata->certholder_umbrella){ ?>
		<?php if($umbrelladata->certholder_umbrella == 'yes'){ $waiver_umbrella = 'checked="checked"'; $class_certholder_umbrella = 'styled'; }?>
		<li><input type="checkbox" value="yes" name="certholder_umbrella" <?php echo $waiver_umbrella; ?> class="<?php echo $class_certholder_umbrella; ?>" /><label> MyVendorCenter listed as Cert. Holder</label></li>
		<?php } ?>	
		</ul>
	</td></tr>
	<tr id="umbrellaliability_sub"></tr>
	<?php
		
		if($licdata || $exist_lic){ $lic_main = 'checked="checked"'; $class_lic = 'styled'; 
	?>
	<tr><td><input type="checkbox" value="yes" id="licensingliability" class="<?php echo $class_lic; ?>" name="licensingliability" <?php echo $lic_main; ?> /></td><td><strong>Licensing </strong></td></tr>
	<?php } ?>
	<tr><td></td><td>
	<ul class="pre_lic" style="pointer-events:none; list-style-type:none;">
		<?php if($licdata->professional  || $exist_lic[1]->req_subparentid){ ?>
		<?php if($licdata->professional == 'yes'  || $exist_lic[1]->req_subparentid){ $professional = 'checked="checked"'; $class_professional = 'styled';}?>
		<li><input type="checkbox" value="yes" name="professional" <?php echo $professional; ?> class="<?php echo $class_professional; ?>" /><label>Professional License</label></li>
		<?php } ?>		
		<?php if($licdata->occupational || $exist_lic[0]->req_subparentid){ ?>
		<?php if($licdata->occupational == 'yes' || $exist_lic[0]->req_subparentid){ $occupational = 'checked="checked"'; $class_occupational = 'styled';}?>
		<li><input type="checkbox" value="yes" name="occupational" <?php echo $occupational; ?> class="<?php echo $class_occupational; ?>" /><label>Occupational License</label></li>
		<?php } ?>	
		</ul>
	</td></tr>
	
	<tr id="licensingliability_sub"></tr>	
	</table>
<!-- eof line item pan -->
<p style="padding-top: 20px;"></p>
<div id="i_bar_terms">
<div id="i_bar_txt_terms">
<span> <font style="font-weight:bold; color:#FFF;">&nbsp;INVITED VENDORS (List is NOT visible to Vendors)</font></span>
</div></div>
<div class="lineitem_pan" style="border:none;">
<?php 
//echo "<pre>"; print_r($this->invitations); echo "</pre>";
$items = $this->invitations ;
 ?>
<div id="heading_vendors_inv">
<div class="company_vendor_inv">COMPANY</div>
<div class="apple_vendor_inv">APPLE RATING</div>
<div class="compliant_vendor_inv">COMPLIANCE STATUS</div>
</div>
<?php 
if($items) {
foreach($items as $am ) {  
?>
<div id="preferredvendorsinvitations" style="width:657px;">
        <div class="search-panel-left_rfp_inv company_vendor_inv">
	
      <ul>
        <li><strong>
		<a href="index.php?option=com_camassistant&controller=vendors&task=vendordetailslayout&id=<?php echo $am->vendorid; ?>" target="_blank"><?php echo $am->company_name; ?></a></strong></li>
        <li><?php echo $am->name; ?> <?php echo $am->lastname; ?>: <?php echo $am->company_phone; ?>	<?php if($am->phone_ext){ echo "&nbsp;Ext.".$am->phone_ext; } ?></li>
		<?php
		$db = & JFactory::getDBO();
	$statecode  = "SELECT code from #__cam_vendor_states where id=".$am->state." " ; 
	$db->setQuery($statecode);
	$statea = $db->loadResult(); 
	?>
	<li><?php echo $am->city; ?>,&nbsp;<?php echo strtoupper($statea); ?></li>
        
        <li><a style="color:gray; font-weight:normal"  href="mailto:<?php echo $am->email; ?>?cc=support@myvendorcenter.com"><?php echo $am->email; ?></a></li>
        </ul>
		
		
		
      </div>
	 
    <div class="search-panel-right_rfp_inv apple_vendor_inv">
	<?php
	$db = & JFactory::getDBO();
$ratecount = "SELECT V.apple FROM `#__cam_vendor_proposals` as U, `#__cam_rfpinfo` as V where U.proposedvendorid=".$am->vendorid." and V.apple!=0 and V.apple_publish=0 and U.proposaltype='Awarded' and U.rfpno = V.id ";
	$db->setQuery($ratecount);
	$count_vs=$db->loadObjectList();
	//To get the CAMA rAting
		$camratingf = "SELECT camrating FROM `#__users` where id=".$am->vendorid."  ";
		$db->setQuery($camratingf);
		$cam_ratingf = $db->loadResult();
		
		if($count_vs){
		for($c=0; $c<count($count_vs); $c++){
		$total = $total + $count_vs[$c]->apple ;
		}
		$camrating = "SELECT camrating FROM `#__users` where id=".$am->vendorid."  ";
		$db->setQuery($camrating);
		$cam_rating = $db->loadResult();
		
		if($cam_rating) {
		$total = $total + $cam_rating ;
		$count = count($count_vs) + 1;
		$avgrating = $total  / $count;	
		$rating =  round($avgrating, 1); 
		}
		else {
		$avgrating = $total  / count($count_vs);	
		$rating =  round($avgrating, 1); 
		}
	}
	else if($cam_ratingf){
	$rating = round($cam_ratingf, 1); 
	}
	else{
	$rating = 4 ;
	}
	
			if ($rating > 0 && $rating <= 0.50)
			{ $rate_image = $rateimage.'5.png';  $rating='0.5'; }
			elseif ($rating > 0.50 && $rating <= 1.00)
			{ $rate_image = $rateimage.'10.png'; $rating='1'; }
			elseif ($rating > 1.00 && $rating <= 1.50)
			{ $rate_image = $rateimage.'10.png'; $rating='1.5';}
			elseif ($rating > 1.50 && $rating <= 2.00)
			{ $rate_image = $rateimage.'20.png'; $rating='2';}
			elseif ($rating > 2.00 && $rating <= 2.50)
			{ $rate_image = $rateimage.'20.png'; $rating='2.5';}
			elseif ($rating > 2.50 && $rating <= 3.00)
			{ $rate_image = $rateimage.'30.png'; $rating='3';}
			elseif ($rating > 3.00 && $rating <= 3.50)
			{ $rate_image = $rateimage.'30.png'; $rating='3.5';}
			elseif ($rating > 3.50 && $rating <= 4.00)
			{ $rate_image = $rateimage.'40.png'; $rating='4';}
			elseif ($rating > 4.00 && $rating <= 4.50)
			{ $rate_image = $rateimage.'40.png'; $rating='4.5';}
			elseif ($rating > 4.50 && $rating <= 5.00)
			{ $rate_image = $rateimage.'50.png'; $rating='5';}
			else
			{ $rate_image = $rateimage.'40.png'; $rating='4';} 
			$total = 0; ?>
			<img width="130" src="templates/camassistant_left/images/<?php echo $rate_image ?>" />
			
	</div>
	
	<div class="search-panel-image_rfp_inv compliant_vendor_inv">
	  <?php 
			if($am->special_requirements == 'fail') {
			$images_text = 'NON-COMPLIANT';
			$compliant_id = "noncompliant";
			}
			else {
			$images_text = 'COMPLIANT';
			$compliant_id = 'compliant';			
			}
			?>
	  <p align="center" style="color:<?php echo $spe_color; ?>; display:block; margin-bottom:7px; font-weight:bold;">
	   <?php if($globals != 'fail'){ ?>
	<a id="<?php echo $compliant_id; ?>" class="modal" rel="{handler: 'iframe', size: {x: 650, y: 800}}" href="index.php?option=com_camassistant&controller=rfp&task=getcompliance&rfpid=<?php echo $rfpinfo->id; ?>&vendorid=<?php echo $am->vendorid; ?>"><?php echo $images_text ; ?></a>
	<?php } else {
			echo "N/A";
			}?>
			 </p>
	  </div>
	  
	  
    <div class="clr"></div>
  </div>
  <?php } 
  }
  ?>
<?php 
/*for($in=0; $in<count($this->invitations); $in++){
$invites = &$this->invitations[$in];
echo "<strong>Company: </strong>".$invites->company_name.'<br />' ;
}*/
?>
</div>
<br />
<div align="center" id="topborder_row" style="background:none;"><table><tr>
<?php if($_REQUEST['var'] != 'view'){ ?>
<td><a style="vertical-align:top" href="javascript:PrintDiv();"><img src="templates/camassistant_left/images/PRINT.gif" border="0" /></a></td>
<td><a style="vertical-align:top" href="index.php?option=com_camassistant&controller=rfp&task=editrfp&show=1&rfpid=<?php echo $rfpinfo->id; ?>&Itemid=<?php echo $_REQUEST['Itemid']; ?>" ><img src="templates/camassistant_left/images/GoBacknew.gif" border="0" /></a></td>
<td><a href="#" onclick="javascript:fn_submitRFP('rfp');" ><img src="templates/camassistant_left/images/Submit.gif" style="padding:0px;" border="0" /></a></td>

<?php } ?>
<?php if($_REQUEST['var'] == 'view'){ ?> 
<td><a style="vertical-align:top" href="javascript:PrintDiv();"><img src="templates/camassistant_left/images/PRINT.gif" border="0" /></a></td>
<td><a href="javascript:history.go(-1)">
<img src="templates/camassistant_left/images/GoBack.gif" alt="Cancel" style="vertical-align:middle; padding-right:0px;"/>
</a></td><?php } ?></tr>

</table>
</div>
<input type="hidden" name="option" value="com_camassistant" />
<input type="hidden" name="task" value="saverfpmsg" />
<input type="hidden" name="rfpid" value="<?php echo $rfpinfo->id; ?>" />
<input type="hidden" name="rfp_type" value="<?php echo $_REQUEST['rfp_type']; ?>" />
<input type="hidden" name="controller" value="rfp" />
<input type="hidden" name="property_id" value="<?php echo $_REQUEST['property_id'];?>" />
<input type="hidden" name="industry_id" value="<?php echo $_REQUEST['industry_id'];?>" />
<input type="hidden" name="Itemid" value="<?php echo $_REQUEST['Itemid'];?>" />
<?php echo JHTML::_( 'form.token' ); ?>

</form>
</div>
<!-- eof table pan -->

</div>