<?php
/**
 * @version		1.0.0 camsignup $
 * @package		camsignup
 * @copyright	Copyright © 2010 - All rights reserved.
 * @license		GNU/GPL
 * @author		anand kumar
 * @author mail	nobody@nobody.com
 *
 *
 * @MVC architecture generated by MVC generator tool at http://www.alphaplug.com
 */

// no direct access
defined('_JEXEC') or die('Restricted access');

// Your custom code here

//echo "<pre>"; print_r($this->details); 
?>
<?php
$user = JFactory::getUser();
if(!$user->id){
echo "<span class='blueheads'>You need to login to access this page</span>";
}
else { ?>
<div id="bedcrumb">
<ul>
<li class="home"><a href="index.php">Home  </a></li><li>Unsubmitted (Draft) RFPs </li>
</ul>
</div>

<?php if($this->details1){ ?>
<div id="dotshead_blue">UNSUBMITTED (DRAFT) RFPS</div>
<div id="i_bar">
<div id="i_icon"><?php 
 $user = JFactory::getUser();  
if ($user->user_type=='12') { ?>

<a style="text-decoration: none;" title="Click here" class="modal" rel="{handler: 'iframe', size: {x: 680, y: 530}}" href="index2.php?option=com_content&amp;view=article&amp;id=133&amp;Itemid=113"><img src="templates/camassistant_left/images/info_icon2.png" /> </a>
<?php } else { ?>
<a style="text-decoration: none;" title="Click here" class="modal" rel="{handler: 'iframe', size: {x: 680, y: 530}}" href="index2.php?option=com_content&amp;view=article&amp;id=132&amp;Itemid=113"><img src="templates/camassistant_left/images/info_icon2.png" /> </a>
<?php } ?></div>
<div id="i_bar_txt">
<span>UNSUBMITTED (DRAFT) RFPS</span>
</div></div>
<div class="table_pannel">
<div class="table_panneldiv">
<table width="100%" cellpadding="0" cellspacing="4">
  <tr class="table_green_row">
    <td width="70" align="center" valign="top">RFP#</td>
    <td width="157" align="center" valign="top">PROPERTY NAME</td>
    <td width="231" align="center" valign="top">PROJECT NAME</td>
    <td width="76" align="center" valign="top">Created</td>
    <td width="120" align="center" valign="top"># OPTIONS</td>
  </tr>
  
  	<?php
	$k = 0;
	foreach ($this->details1 as $row1) :
	//for ($i=0, $n=count( $this->details1 ); $i < $n; $i++)
	//{
		//$row1 = &$this->details1[$i];
       // echo "<pre>"; print_r($row);
		//$link 	= JRoute::_( 'index.php?option=com_camassistant&controller=category_detail&task=edit&cid[]='. $row->id );

		//$checked 	= JHTML::_('grid.checkedout',   $row, $i );
		//$published 	= JHTML::_('grid.published', $row, $i );		

		?>
		  <tr class="table_blue_rowdots">
			
			<td align="center" valign="top"><?php echo sprintf('%06d', $row1->id); //echo $row1->id; ?></td>
	 		<td align="left" valign="middle"><?php echo $row1->property_name; ?></td>		
			<td align="left" valign="top"><?php echo $row1->projectName; ?></td>
	   		<td align="center" valign="top"><?php echo $row1->createdDate; ?></td>
    		<td align="center" valign="middle"><a href="index.php?option=com_camassistant&controller=rfp&task=editrfp&var=draft&rfpid= <?php echo $row1->id;  ?>&Itemid=<?php echo $_REQUEST['Itemid']; ?>">EDIT</a> <?php /*?><img hspace="8" alt="liks devider" src="templates/camassistant_left/images/links_devider.gif"> <a href="index.php?option=com_camassistant&controller=rfpcenter&task=updateunsubmited&id=<?php echo $row1->id; ?>&Itemid=<?php echo $_REQUEST['Itemid'];?>">SUBMIT</a><?php */?></td>
	

  
  </tr>
  </tr>
		<?php
		$k = 1 - $k;
		endforeach;
	//}
	?>
 <tr class="table_blue_rowdots">
   <td align="center" valign="top"></td>
   <td align="left" valign="middle"></td>
   <td align="left" valign="top"></td>
   <td align="left" valign="top"></td>
   <td align="center" valign="middle"></td>
 </tr>
 
 
</table>
<div class="clear"></div>
</div>
</div>
<?php } else { ?>
<div>You don't have any unsubmitted(draft) rfp's</div>
<?php } ?>
<?php if($this->details1){ ?>
<?php if($_REQUEST['viewall']!='all'){ ?>
<a href="index.php?option=com_camassistant&controller=rfpcenter&task=unsubmittedrfp&viewall=all&Itemid=<?php echo $_REQUEST['Itemid'];?>" ><img src="templates/camassistant_left/images/view_all.gif" border="0"/></a>
<?php } ?>
<?php if ($_REQUEST['viewall']=='all') { ?>
<a href="index.php?option=com_camassistant&controller=rfpcenter&task=unsubmittedrfp&Itemid=<?php echo $_REQUEST['Itemid'];?>" ><img src="templates/camassistant_left/images/back1.gif" border="0" /></a>
<?php } 
}
?>
	<?php echo $this->pagination1->getPagesLinks( ); ?>
	<?php //echo $this->pagination1->getLimitBox( ); ?>
	<?php echo $this->pagination1->getResultsCounter(); ?>
</div>
<?php } ?>